# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Пицерия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('urls', models.URLField(verbose_name='Интернет адресс')),
            ],
        ),
    ]
