# Generated by Django 2.1.7 on 2019-02-22 09:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clocks',
            fields=[
                ('clocks_id', models.AutoField(primary_key=True, serialize=False)),
                ('lections', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('lab', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('practics', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ksr', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('srs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('control', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Часы',
                'verbose_name_plural': 'Часы',
            },
        ),
        migrations.CreateModel(
            name='Compititions',
            fields=[
                ('compititions_id', models.AutoField(primary_key=True, serialize=False)),
                ('compititions_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Компетенции',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('discipline_shifr', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('disc_index', models.CharField(max_length=50)),
                ('ZET', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Element_Ymk',
            fields=[
                ('element_id', models.AutoField(primary_key=True, serialize=False)),
                ('element_shifr', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('element_anme', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'УМК',
                'verbose_name_plural': 'УМК',
            },
        ),
        migrations.CreateModel(
            name='Form_cotrol',
            fields=[
                ('form_cotrol_id', models.AutoField(primary_key=True, serialize=False)),
                ('form_cotrol_semestr', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipline', to='excelapp.Discipline')),
            ],
            options={
                'verbose_name': 'Формы контроля',
                'verbose_name_plural': 'Формы контроля',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_number', models.CharField(default=1, max_length=50)),
                ('institut', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('forma_obuch', models.CharField(max_length=10)),
                ('kolvochel', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('yslovie', models.CharField(max_length=50)),
                ('normativy', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Individ',
            fields=[
                ('individ_id', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.CharField(max_length=50)),
                ('name_rabot', models.CharField(max_length=50)),
                ('tredoem', models.CharField(max_length=50)),
                ('forma_finish', models.CharField(max_length=50)),
                ('srok_vip', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Индивидуальный учебный план',
                'verbose_name_plural': 'Индивидуальный учебный план',
            },
        ),
        migrations.CreateModel(
            name='IndividYr',
            fields=[
                ('individyr_id', models.AutoField(primary_key=True, serialize=False)),
                ('kolvo_chasov', models.CharField(max_length=10)),
                ('individ_god', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('individyr_id_discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individyr_discipline', to='excelapp.Discipline')),
            ],
            options={
                'verbose_name': 'Индивидуальный учебный план по У.Р.',
                'verbose_name_plural': 'Индивидуальный учебный план по У.Р.',
            },
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('kafedra_id', models.AutoField(primary_key=True, serialize=False)),
                ('kafedra_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедра',
            },
        ),
        migrations.CreateModel(
            name='Napravlenie',
            fields=[
                ('napravlenie_id', models.AutoField(primary_key=True, serialize=False)),
                ('napravlenie_shifr', models.CharField(default=0, max_length=50)),
                ('napravlenie_name', models.CharField(max_length=50)),
                ('profil', models.CharField(max_length=50)),
                ('kvalification', models.CharField(max_length=50)),
                ('nomer_fgos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('napravlenie_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направление',
            },
        ),
        migrations.CreateModel(
            name='Normi',
            fields=[
                ('normi_id', models.AutoField(primary_key=True, serialize=False)),
                ('vid_rabot', models.CharField(max_length=50)),
                ('normi_chas', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('primechanie', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Нормы времени учебной работы',
                'verbose_name_plural': 'Нормы времени учебной работы',
            },
        ),
        migrations.CreateModel(
            name='Otchet',
            fields=[
                ('otchet_id', models.AutoField(primary_key=True, serialize=False)),
                ('god', models.DateField()),
                ('pokazatel', models.CharField(max_length=50)),
                ('svedeniya', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Отчет о работе преподавателя',
                'verbose_name_plural': 'Отчет о работе преподавателя',
            },
        ),
        migrations.CreateModel(
            name='Praktiki',
            fields=[
                ('praktiki_id', models.AutoField(primary_key=True, serialize=False)),
                ('praktiki_name', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
            },
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('prepod_id', models.AutoField(primary_key=True, serialize=False)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otchestvo', models.CharField(max_length=50)),
                ('zvanie', models.CharField(max_length=50)),
                ('uch_step', models.CharField(max_length=50)),
                ('doljnost', models.CharField(max_length=50)),
                ('date_izbran', models.DateField()),
                ('prepod_kafedra', models.CharField(max_length=50)),
                ('facultet', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватель',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_semestr', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('session_date_start', models.DateField()),
                ('session_date_finish', models.DateField()),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессия',
            },
        ),
        migrations.CreateModel(
            name='Sroki',
            fields=[
                ('sroki_id', models.AutoField(primary_key=True, serialize=False)),
                ('sroki_semestr', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_praktiki', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='excelapp.Praktiki')),
            ],
            options={
                'verbose_name': 'Сроки',
                'verbose_name_plural': 'Сроки',
            },
        ),
        migrations.CreateModel(
            name='UchPlan',
            fields=[
                ('uchPlan_id', models.AutoField(primary_key=True, serialize=False)),
                ('uchPlan_shifr', models.CharField(default=0, max_length=50)),
                ('god_start', models.DateField()),
                ('protocol', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_protocol', models.DateField()),
                ('uchPlan_kafedra', models.CharField(max_length=50)),
                ('uchplan_profil', models.CharField(max_length=50)),
                ('facultet', models.CharField(max_length=50)),
                ('id_napravlenie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='napravlenie', to='excelapp.Napravlenie')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебный план',
            },
        ),
        migrations.CreateModel(
            name='UchPlanVidydeyt',
            fields=[
                ('UchPlanVidydeyt_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Уч.пдан-Виды деят',
                'verbose_name_plural': 'Уч.План-Виды деят',
            },
        ),
        migrations.CreateModel(
            name='Vid_control',
            fields=[
                ('vid_control_id', models.AutoField(primary_key=True, serialize=False)),
                ('vid_control_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Вид контроля',
                'verbose_name_plural': 'Вид контроля',
            },
        ),
        migrations.CreateModel(
            name='Vidy_deyt',
            fields=[
                ('Vidy_deyt_id', models.AutoField(primary_key=True, serialize=False)),
                ('Vidy_deyt_name', models.CharField(max_length=50)),
                ('id_napravlenie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excelapp.Napravlenie')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Вид деятельности',
            },
        ),
        migrations.CreateModel(
            name='Ymk',
            fields=[
                ('ymk_id', models.AutoField(primary_key=True, serialize=False)),
                ('ymk_shifr', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ymk_id_discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ymk_discipline', to='excelapp.Discipline')),
                ('ymk_id_prepod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ymk_prepod', to='excelapp.Prepod')),
                ('ymk_id_uchPlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ymk_uchPlan', to='excelapp.UchPlan')),
            ],
            options={
                'verbose_name': 'УМК',
                'verbose_name_plural': 'УМК',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='session_id_uchPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_uchplan', to='excelapp.UchPlan'),
        ),
        migrations.AddField(
            model_name='praktiki',
            name='praktiki_id_uchPlan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='prictiki_uchplan', to='excelapp.UchPlan'),
        ),
        migrations.AddField(
            model_name='otchet',
            name='otchet_id_prepod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otchet_prepod', to='excelapp.Prepod'),
        ),
        migrations.AddField(
            model_name='individyr',
            name='individyr_id_prepod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individyr_prepod', to='excelapp.Prepod'),
        ),
        migrations.AddField(
            model_name='individyr',
            name='indiviryr_id_normi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individyr_normi', to='excelapp.Normi'),
        ),
        migrations.AddField(
            model_name='individ',
            name='id_mormi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individ_normi', to='excelapp.Normi'),
        ),
        migrations.AddField(
            model_name='individ',
            name='individ_id_prepod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individ_prepod', to='excelapp.Prepod'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_id_napravlenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_napravlenie', to='excelapp.Napravlenie'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_id_uchPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_uchPlan', to='excelapp.UchPlan'),
        ),
        migrations.AddField(
            model_name='form_cotrol',
            name='id_vid_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vid_control', to='excelapp.Vid_control'),
        ),
        migrations.AddField(
            model_name='element_ymk',
            name='id_ymk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='element_ymk', to='excelapp.Ymk'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='id_kafedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kafedra', to='excelapp.Kafedra'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='id_prepod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepod', to='excelapp.Prepod'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='id_uchPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uchPlan', to='excelapp.UchPlan'),
        ),
        migrations.AddField(
            model_name='clocks',
            name='clocks_id_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipline_clocks', to='excelapp.Discipline'),
        ),
    ]
