# Generated by Django 2.1.7 on 2019-02-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='discipline',
            field=models.ManyToManyField(related_name='discipline_group', to='excelapp.Discipline'),
        ),
    ]
