# Generated by Django 2.1.7 on 2019-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0002_group_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файл',
            },
        ),
        migrations.AlterModelOptions(
            name='element_ymk',
            options={'verbose_name': 'УМК элемент', 'verbose_name_plural': 'УМК элемент'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='discipline',
        ),
    ]
