# Generated by Django 2.1.7 on 2019-03-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0003_auto_20190222_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompititionsDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compititionsdiscipline_comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compititionsdiscipline_comp', to='excelapp.Discipline')),
                ('compititionsdiscipline_disc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compititionsdiscipline_disc', to='excelapp.Compititions')),
            ],
            options={
                'verbose_name': 'Компетенция-Дисциплина',
                'verbose_name_plural': 'Компетенции-Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='CompititionsPraktiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compititionsPraktiki_comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compititionsPraktiki_comp', to='excelapp.Compititions')),
                ('compititionsPraktiki_prakt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compititionsPraktiki_prakt', to='excelapp.Praktiki')),
            ],
            options={
                'verbose_name': 'Компетенция-Практика',
                'verbose_name_plural': 'Компетенции-Практики',
            },
        ),
        migrations.CreateModel(
            name='ElementYmkUchPlan',
            fields=[
                ('ElementYmkUchPlan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Элемент УМК - Уч. План',
                'verbose_name_plural': 'Элементы УМК - Уч. Планы',
            },
        ),
        migrations.CreateModel(
            name='GroupDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupdiscipline_discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupdiscipline_discipline', to='excelapp.Discipline')),
                ('groupdiscipline_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupdiscipline_group', to='excelapp.Group')),
            ],
            options={
                'verbose_name': 'Группа-Дисциплина',
                'verbose_name_plural': 'Группы-Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Posobia',
            fields=[
                ('posobia_id', models.AutoField(primary_key=True, serialize=False)),
                ('posobia_god', models.DateField()),
                ('posobia_status', models.CharField(max_length=50)),
                ('id_ElementYmkUchPlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_ElementYmkUchPlan', to='excelapp.ElementYmkUchPlan')),
            ],
            options={
                'verbose_name': 'Пособие',
                'verbose_name_plural': 'Пособия',
            },
        ),
        migrations.AlterModelOptions(
            name='uchplan',
            options={'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебныеt планы'},
        ),
        migrations.AlterModelOptions(
            name='vidy_deyt',
            options={'verbose_name': 'Вид деятельности', 'verbose_name_plural': 'Виды деятельности'},
        ),
        migrations.AddField(
            model_name='uchplanvidydeyt',
            name='UchPlanVidydeyt_shifr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='excelapp.UchPlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uchplanvidydeyt',
            name='UchPlanVidydeyt_vidydeyt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='excelapp.Vidy_deyt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementymkuchplan',
            name='ElementYmkUchPlan_uchplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ElementYmkUchPlan_uchplan', to='excelapp.UchPlan'),
        ),
        migrations.AddField(
            model_name='elementymkuchplan',
            name='ElementYmkUchPlan_ymk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ElementYmkUchPlan_ymk', to='excelapp.Element_Ymk'),
        ),
    ]
