# Generated by Django 2.1.7 on 2019-03-17 20:31

from django.db import migrations, models
import excelapp.views


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0004_auto_20190313_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'файл', 'verbose_name_plural': 'файлы'},
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='media/', validators=[excelapp.views.valid_file]),
        ),
        migrations.AlterField(
            model_name='napravlenie',
            name='profil',
            field=models.CharField(max_length=100),
        ),
    ]
