# Generated by Django 2.1.7 on 2019-03-22 18:40

import django.core.validators
from django.db import migrations, models
import excelapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0005_auto_20190317_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(storage=excelapp.models.ReplacingFileStorage(), upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
    ]
