# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цветов',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Топлива',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марок',
            },
        ),
        migrations.CreateModel(
            name='ModelCar',
            fields=[
                ('model_car_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('id_fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCar.Fuel')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классов',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.PositiveIntegerField()),
                ('id_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCar.Auto')),
                ('id_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCar.Operator')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренд',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('tariff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифов',
            },
        ),
        migrations.AddField(
            model_name='rent',
            name='id_tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCar.Tariff'),
        ),
        migrations.AddField(
            model_name='modelcar',
            name='id_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCar.Rank'),
        ),
        migrations.AddField(
            model_name='modelcar',
            name='mark_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCar.Mark'),
        ),
        migrations.AddField(
            model_name='auto',
            name='id_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCar.Color'),
        ),
        migrations.AddField(
            model_name='auto',
            name='id_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCar.Mark'),
        ),
    ]
