# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='photo',
        ),
        migrations.AddField(
            model_name='modelcar',
            name='photo',
            field=models.ImageField(blank=True, upload_to='MyCar/media'),
        ),
    ]
