# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=50)),
                ('equipment_price', models.IntegerField()),
                ('equipment_size', models.IntegerField(default=0)),
                ('equipment_date', models.DateField()),
                ('equipment_country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Equipment_type',
            fields=[
                ('et_id', models.AutoField(primary_key=True, serialize=False)),
                ('et_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудований',
            },
        ),
        migrations.CreateModel(
            name='Equpment_type_seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('et_id_f', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='database.Equipment_type')),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('firm_id', models.AutoField(primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=50)),
                ('firm_address', models.CharField(max_length=50)),
                ('firm_country', models.CharField(max_length=30)),
                ('firm_number', models.CharField(max_length=50)),
                ('firm_site', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирмы',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_address', models.CharField(max_length=50)),
                ('provider_country', models.CharField(max_length=30)),
                ('provider_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_address', models.CharField(max_length=50)),
                ('seller_exp', models.IntegerField()),
                ('provider_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.AddField(
            model_name='equpment_type_seller',
            name='sel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='database.Seller'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='id_equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Equipment_type'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='id_firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Firm'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='id_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Provider'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='id_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Seller'),
        ),
    ]
