from django.conf.urls import url
from MyCar import views
urlpatterns = [
    url(r'^main_page/$', views.main_page, name="main_page"),
    url(r'^auto/$', views.auto, name="auto"),
    url(r"^model/(?P<model_id>\d+)$", views.model, name="model"),
    url(r"^tariff/$", views.tariff, name="tariff"),
    url(r"^operators/$", views.operators, name="operators"),
    url(r"^about/$", views.about, name="about"),
    url(r"^admin_menu/$", views.admin_menu, name="admin_menu"),
    url(r"^show_rent/$", views.show_rent, name="show_rent"),
    url(r"^show_rank/$", views.show_rank, name="show_rank"),
    url(r"^show_mark_models/$", views.show_mark, name="show_mark"),
    url(r"^models/(?P<id_mark>\d+)$", views.show_models, name="show_models"),
    url(r"^fuel/$", views.show_fuel, name="show_fuel"),
    url(r"^operator/$", views.show_operator, name="show_operator"),
    url(r"^tariffs/$", views.show_tariffs, name="show_tariffs"),
    url(r"^add_rank/$", views.add_rank, name="add_rank"),
    url(r"^add_mark/$", views.add_mark, name="add_mark"),
    url(r"^add_operator/$", views.add_operator, name="add_operator"),
    url(r"^add_tariff/$", views.add_tariff, name="add_tariff"),
    url(r"^add_fuel/$", views.add_fuel, name="add_fuel"),
    url(r"^add_model/$", views.add_model, name="add_model"),
    url(r"^edit_rank/(?P<rank_id>\d+)$", views.edit_rank, name="edit_rank"),
    url(r"^edit_mark/(?P<mark_id>\d+)$", views.edit_mark, name="edit_mark"),
    url(r"^edit_model/(?P<model_id>\d+)$", views.edit_model, name="edit_model"),
    url(r"^edit_tariff/(?P<tariff_id>\d+)$", views.edit_tariff, name="edit_tariff"),
    url(r"^edit_fuel/(?P<fuel_id>\d+)$", views.edit_fuel, name="edit_fuel"),
    url(r"^edit_rent/(?P<rent_id>\d+)$", views.edit_rent, name="edit_rent"),
    url(r"^edit_operator/(?P<operator_id>\d+)$", views.edit_operator, name="edit_operator"),
    url(r"^delete_rent/(?P<rent_id>\d+)$", views.delete_rent, name="delete_rent"),
    url(r"^delete_rank/(?P<rank_id>\d+)$", views.delete_rank, name="delete_rank"),
    url(r"^delete_operator/(?P<operator_id>\d+)$", views.delete_operator, name="delete_operator"),
    url(r"^delete_tariff/(?P<tariff_id>\d+)$", views.delete_tariff, name="delete_tariff"),
    url(r"^delete_fuel/(?P<fuel_id>\d+)$", views.delete_fuel, name="delete_fuel"),
    url(r"^delete_mark/(?P<mark_id>\d+)$", views.delete_mark, name="delete_mark"),
    url(r"^delete_model/(?P<model_car_id>\d+)$", views.delete_model, name="delete_model"),

]