# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airports',
            fields=[
                ('airports_id', models.AutoField(primary_key=True, serialize=False)),
                ('airports_code', models.IntegerField()),
                ('airports_name', models.CharField(max_length=10)),
                ('airports_city', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='boarding_pass',
            fields=[
                ('boarding_pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('boarding_pass_number', models.CharField(max_length=20)),
                ('mesto', models.CharField(max_length=3)),
                ('exit', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Посадочный талон',
                'verbose_name_plural': 'Посадочные талоны',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('company_phone_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Проихводитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='flight_conditions',
            fields=[
                ('flight_conditions_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_conditions_name', models.CharField(max_length=30)),
                ('vozvrat', models.CharField(max_length=10)),
                ('baggage', models.IntegerField()),
                ('animals', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Условия перелета',
                'verbose_name_plural': 'Условие перелета',
            },
        ),
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('passport', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('first_name', models.CharField(max_length=50)),
                ('otchestvo', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Дожность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('tickets_id', models.AutoField(primary_key=True, serialize=False)),
                ('tickets_number', models.IntegerField()),
                ('flight', models.CharField(max_length=10)),
                ('tickets_price', models.FloatField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('tickets_date', models.DateField()),
                ('id_boarding_pass', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.boarding_pass')),
                ('id_flight_conditions', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='avia.flight_conditions')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
