# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('contacts_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.AddField(
            model_name='passenger',
            name='id_contacts',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='avia.contacts'),
        ),
    ]
