# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0002_auto_20180517_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='id_passenger',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.passenger'),
        ),
    ]
