# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0003_tickets_id_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='aircrafts',
            fields=[
                ('aircrafts_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
            },
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=30)),
                ('vilet_time', models.DateField()),
                ('prilet_time', models.DateField()),
                ('flight_departure', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.airports')),
                ('id_aircrafts', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.aircrafts')),
            ],
            options={
                'verbose_name': 'Рейсы',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='model_aircraft',
            fields=[
                ('model_aircraft_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_aircraft_name', models.CharField(max_length=30)),
                ('kolvo_mest', models.IntegerField()),
                ('max_dal', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('id_company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.company')),
            ],
            options={
                'verbose_name': 'Модель самолета',
                'verbose_name_plural': 'Модель самолета',
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('grafik', models.CharField(max_length=10)),
                ('FIO', models.CharField(max_length=60)),
                ('id_aircrafts', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.aircrafts')),
                ('id_post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.post')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='aircrafts',
            name='model_aircraft_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.model_aircraft'),
        ),
    ]
