# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0004_auto_20180518_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='flight',
            new_name='tickets_flight',
        ),
        migrations.AddField(
            model_name='tickets',
            name='id_flight',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id_aircrafts',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='avia.aircrafts'),
        ),
    ]
