# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0005_auto_20180518_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_arrival',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='avia.airports'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_departure',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='avia.airports'),
        ),
    ]
